package app.model;
// Generated 09/11/2017 08:42:15 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "example_db")
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class,property="@id")
public class Alumno implements java.io.Serializable {

	private Integer alumnoId;
	private String nombres;
	private String apellidos;
	private BigDecimal promedio;
	private Character status;
	private Set<AulaAlumno> aulaAlumnos = new HashSet<AulaAlumno>(0);

	public Alumno() {
	}

	public Alumno(String nombres, String apellidos, BigDecimal promedio, Character status,
			Set<AulaAlumno> aulaAlumnos) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.promedio = promedio;
		this.status = status;
		this.aulaAlumnos = aulaAlumnos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "alumno_id", unique = true, nullable = false)
	public Integer getAlumnoId() {
		return this.alumnoId;
	}

	public void setAlumnoId(Integer alumnoId) {
		this.alumnoId = alumnoId;
	}

	@Column(name = "nombres", length = 100)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", length = 150)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "promedio", precision = 5)
	public BigDecimal getPromedio() {
		return this.promedio;
	}

	public void setPromedio(BigDecimal promedio) {
		this.promedio = promedio;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
	public Set<AulaAlumno> getAulaAlumnos() {
		return this.aulaAlumnos;
	}

	public void setAulaAlumnos(Set<AulaAlumno> aulaAlumnos) {
		this.aulaAlumnos = aulaAlumnos;
	}

}
