package app.model;
// Generated 09/11/2017 08:42:15 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * AulaAlumno generated by hbm2java
 */
@Entity
@Table(name = "aula_alumno", catalog = "example_db")
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class,property="@id")
public class AulaAlumno implements java.io.Serializable {

	private Integer aulaAlumnoId;
	private Alumno alumno;
	private Aula aula;

	public AulaAlumno() {
	}

	public AulaAlumno(Alumno alumno, Aula aula) {
		this.alumno = alumno;
		this.aula = aula;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "aula_alumno_id", unique = true, nullable = false)
	public Integer getAulaAlumnoId() {
		return this.aulaAlumnoId;
	}

	public void setAulaAlumnoId(Integer aulaAlumnoId) {
		this.aulaAlumnoId = aulaAlumnoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alumno_id", nullable = false)
	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aula_id", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

}
