package app.model;
// Generated 06/05/2018 07:04:29 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DataTb02 generated by hbm2java
 */
@Entity
@Table(name = "data_tb_02", schema = "dbo")
public class DataTb02 implements java.io.Serializable {

	private Integer id;
	private DataTb01 dataTb01;
	private String fieldThree;
	private String fieldFour;

	public DataTb02() {
	}

	public DataTb02(DataTb01 dataTb01, String fieldThree, String fieldFour) {
		this.dataTb01 = dataTb01;
		this.fieldThree = fieldThree;
		this.fieldFour = fieldFour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tb_01")
	public DataTb01 getDataTb01() {
		return this.dataTb01;
	}

	public void setDataTb01(DataTb01 dataTb01) {
		this.dataTb01 = dataTb01;
	}

	@Column(name = "field_three", length = 50)
	public String getFieldThree() {
		return this.fieldThree;
	}

	public void setFieldThree(String fieldThree) {
		this.fieldThree = fieldThree;
	}

	@Column(name = "field_four", length = 100)
	public String getFieldFour() {
		return this.fieldFour;
	}

	public void setFieldFour(String fieldFour) {
		this.fieldFour = fieldFour;
	}

}
