package app.model;
// Generated 06/05/2018 07:04:29 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedStoredProcedureQueries;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.OneToMany;
import javax.persistence.ParameterMode;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;


/**
 * DataTb01 generated by hbm2java
 */
@Entity
@Table(name = "data_tb_01", schema = "dbo")

@NamedStoredProcedureQueries({
		@NamedStoredProcedureQuery(name = "my_stored_procedure", 
				procedureName = "usp_my_procedure", 
				resultClasses={UvMyView.class},
				parameters = {
				@StoredProcedureParameter(name = "Param1", type = Integer.class, mode = ParameterMode.IN),
				@StoredProcedureParameter(name = "Param2", type = Integer.class, mode = ParameterMode.OUT) }) })
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class,property="@id")
public class DataTb01 implements java.io.Serializable {

	private Integer id;
	private String fieldOne;
	private String fieldTwo;
	private Set<DataTb02> dataTb02s = new HashSet<DataTb02>(0);

	public DataTb01() {
	}

	public DataTb01(String fieldOne, String fieldTwo, Set<DataTb02> dataTb02s) {
		this.fieldOne = fieldOne;
		this.fieldTwo = fieldTwo;
		this.dataTb02s = dataTb02s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "field_one", length = 100)
	public String getFieldOne() {
		return this.fieldOne;
	}

	public void setFieldOne(String fieldOne) {
		this.fieldOne = fieldOne;
	}

	@Column(name = "field_two")
	public String getFieldTwo() {
		return this.fieldTwo;
	}

	public void setFieldTwo(String fieldTwo) {
		this.fieldTwo = fieldTwo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataTb01")
	public Set<DataTb02> getDataTb02s() {
		return this.dataTb02s;
	}

	public void setDataTb02s(Set<DataTb02> dataTb02s) {
		this.dataTb02s = dataTb02s;
	}

	@Override
	public String toString() {
		return "DataTb01 [id=" + id + ", fieldOne=" + fieldOne + ", fieldTwo=" + fieldTwo + ", dataTb02s=" + dataTb02s
				+ "]";
	}
	
	
	
}
