package app.model;
// Generated 06/05/2018 03:30:23 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UvMyView generated by hbm2java
 */
@Entity
@Table(name = "uv_my_view", schema = "dbo")
public class UvMyView implements java.io.Serializable {

	private UvMyViewId id;

	public UvMyView() {
	}

	public UvMyView(UvMyViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "fieldOne", column = @Column(name = "field_one", length = 100)),
			@AttributeOverride(name = "fieldTwo", column = @Column(name = "field_two")),
			@AttributeOverride(name = "countChildren", column = @Column(name = "count_children")) })
	public UvMyViewId getId() {
		return this.id;
	}

	public void setId(UvMyViewId id) {
		this.id = id;
	}

}
