package app.model;
// Generated 06/05/2018 03:30:23 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UvMyViewId generated by hbm2java
 */
@Embeddable
public class UvMyViewId implements java.io.Serializable {

	private int id;
	private String fieldOne;
	private String fieldTwo;
	private Integer countChildren;

	public UvMyViewId() {
	}

	public UvMyViewId(int id) {
		this.id = id;
	}

	public UvMyViewId(int id, String fieldOne, String fieldTwo, Integer countChildren) {
		this.id = id;
		this.fieldOne = fieldOne;
		this.fieldTwo = fieldTwo;
		this.countChildren = countChildren;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "field_one", length = 100)
	public String getFieldOne() {
		return this.fieldOne;
	}

	public void setFieldOne(String fieldOne) {
		this.fieldOne = fieldOne;
	}

	@Column(name = "field_two")
	public String getFieldTwo() {
		return this.fieldTwo;
	}

	public void setFieldTwo(String fieldTwo) {
		this.fieldTwo = fieldTwo;
	}

	@Column(name = "count_children")
	public Integer getCountChildren() {
		return this.countChildren;
	}

	public void setCountChildren(Integer countChildren) {
		this.countChildren = countChildren;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UvMyViewId))
			return false;
		UvMyViewId castOther = (UvMyViewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getFieldOne() == castOther.getFieldOne()) || (this.getFieldOne() != null
						&& castOther.getFieldOne() != null && this.getFieldOne().equals(castOther.getFieldOne())))
				&& ((this.getFieldTwo() == castOther.getFieldTwo()) || (this.getFieldTwo() != null
						&& castOther.getFieldTwo() != null && this.getFieldTwo().equals(castOther.getFieldTwo())))
				&& ((this.getCountChildren() == castOther.getCountChildren())
						|| (this.getCountChildren() != null && castOther.getCountChildren() != null
								&& this.getCountChildren().equals(castOther.getCountChildren())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getFieldOne() == null ? 0 : this.getFieldOne().hashCode());
		result = 37 * result + (getFieldTwo() == null ? 0 : this.getFieldTwo().hashCode());
		result = 37 * result + (getCountChildren() == null ? 0 : this.getCountChildren().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "UvMyViewId [id=" + id + ", fieldOne=" + fieldOne + ", fieldTwo=" + fieldTwo + ", countChildren="
				+ countChildren + "]";
	}
	
	

}
